version: '3.8'

services:
  portfolio:
    image: ghcr.io/kivancturkmen/my-portfolio-web:latest
    networks:
      - proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first

networks:
  proxy:
    external: true
